#!/usr/bin/env bash
#
# This script is run to pull the PaloAlto_Block_IP_List.txt file (maintained through Microsoft Sentinel)
# from Azure storage and mirror it here for the Palo Altos to sync.
#
# Purpose of this is to be in control of our certificate on this server.
# A bad entry in this file coupled with an expired cert (maintained by Microsoft)
# ended in an outage when the certificate was finally renewed.
#
# With this setup, we shouldn't have time bombs like that.
#
# Errors:
#   exit code 1 if curl exits with any code that is not certificate related
#   exit code 2 if we do not get a 2xx response from the URL

set -uo pipefail
# plain curl
# - check rc
# - if rc in cert_error_codes
#   - log the error
#   - rerun curl with -k option
# - if rc -ne 0 && rc not in cert_error_codes
#   - log the error
#   - send an alert
# - validate file (how?)

PATH=/usr/bin

IP_RE='(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}'

ip_v6='(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))'

cert_error_codes=(58 60 77 91 98)

# -s: silent (no console output
# -S: show errors
# -i: Include  the  HTTP  response  headers  in  the output.
curl="curl -s -S -i"

file_location=/usr/share/nginx/html

edl_filename="PaloAlto_Block_IP_List.txt"

stamp=$(date +%F_%R:%S)

temp_file=/tmp/edl_filename_${stamp}

url="https://svc0secops0storageaccnt.blob.core.windows.net/testcont/${edl_filename}"

what_went_wrong() {
    result=$1

    curl_err=$(grep -E "^[[:space:]]+${result}[[:space:]]+" /root/curls_error_codes)
}

get_the_payload() {
    $curl "${url}" > "${temp_file}"
    rc=$?


    # test for success
    if [[ 0 -eq $rc ]]
    then
        grep -E "^$IP_RE.*$" "${temp_file}" > "${file_location}/${edl_filename}"
        logger "curl: $edl_filename synchronized."
        git -C "/opt/edl" add "$edl_filename"
        git -C "/opt/edl" commit -m "$(date --iso-8601=seconds)" >/dev/null

    # check for certificate errors
    elif printf '%s\0' "${cert_error_codes[@]}" | grep -Fxqz -- "$rc"
#    elif [[ 0 -ne $rc && ${cert_error_codes[@]} =~ \b$rc\b ]]
    then
    # log the error
        what_went_wrong $rc
        message="curl: certificate error attempting to get ${url}: ${curl_err}"
        logger "$message"
        curl="$curl -k"
        echo "trying again with $curl"
        get_the_payload

    # test for non-certificate errors
    elif ! printf '%s\0' "${cert_error_codes[@]}" | grep -Fxqz -- "$rc"
    then
        # send alert
        echo "${curl_err}" | mailx -s "curl failure: ${rc}" -r edl_sync@$(hostname) dreynolds@epiqglobal.com Eli.Johnson@epiqglobal.com
        exit 1
    fi

    http_status=$(head -n 1 "${temp_file}" | grep -E -o '[0-9]{3}')

    # bail if we get anything other than a 2xx return code
    if [[ ! "$http_status" =~ ^2 ]]
    then
        message="curl: error $http_status when attempting to sync $edl_filename"
        logger "$message"
        echo "command: $curl ${url}" | sed -E 's#(https?)#\1 #' | mailx -s "$message" -r edl_sync@$(hostname) dreynolds@epiqglobal.com Eli.Johnson@epiqglobal.com
        exit 2
    fi
}


search_for_ipv6() {
    ipv6_entries=$(grep -E "^$ip_v6.*$" "${temp_file}")

    if [[ "${ipv6_entries}" != '' ]]
    then
        echo -e "${ipv6_entries}" | mailx -s "ipv6 entries found in ${edl_filename}" -r edl_sync@$(hostname) dreynolds@epiqglobal.com Eli.Johnson@epiqglobal.com
    fi
}

remove_temp_file() {
    rm -f "${temp_file}"
}



# allow for testing cert errors
if [[ $# -ge 1 && $1 =~ ^https:// ]]
then
    url="$1/foo"
fi
get_the_payload
search_for_ipv6
remove_temp_file
